-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 15:07:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Entity_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entity_Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entity_Usuario` (
  `idEntity_Usuario` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Dt_Nasci` VARCHAR(45) NULL,
  `Telefone_01` VARCHAR(45) NULL,
  `Telefone_02` VARCHAR(45) NULL,
  `Vinculo` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntity_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entity_Usuario_Medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entity_Usuario_Medico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entity_Usuario_Medico` (
  `idEntity_Usuario` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Dt_Nasci` VARCHAR(45) NULL,
  `Telefone_01` VARCHAR(45) NULL,
  `Telefone_02` VARCHAR(45) NULL,
  `Vinculo` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntity_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entity_Agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entity_Agenda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entity_Agenda` (
  `idEntity_Agenda` INT NOT NULL,
  `IdMedico` INT NULL,
  `Entity_Agendacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntity_Agenda`),
  INDEX `FK_Id_Medico_idx` (`IdMedico` ASC) VISIBLE,
  CONSTRAINT `FK_Id_Medico`
    FOREIGN KEY (`IdMedico`)
    REFERENCES `mydb`.`Entity_Usuario_Medico` (`idEntity_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entity_Consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entity_Consulta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entity_Consulta` (
  `idEntity_Consulta` INT NOT NULL,
  `ID_Agenda` INT NULL,
  `ID_Paciente` INT NULL,
  `Ativa` TINYINT NULL DEFAULT 1,
  `Realizada` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idEntity_Consulta`),
  INDEX `FK_Agenda_idx` (`ID_Agenda` ASC) VISIBLE,
  INDEX `FK_Paciente_idx` (`ID_Paciente` ASC) VISIBLE,
  CONSTRAINT `FK_Agenda`
    FOREIGN KEY (`ID_Agenda`)
    REFERENCES `mydb`.`Entity_Agenda` (`idEntity_Agenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Paciente`
    FOREIGN KEY (`ID_Paciente`)
    REFERENCES `mydb`.`Entity_Usuario` (`idEntity_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entity_Procedimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entity_Procedimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entity_Procedimento` (
  `idEntity_Procedimento` INT NOT NULL,
  `ID_Medico` INT NULL,
  `ID_Paciente` INT NULL,
  `Descricao` VARCHAR(45) NULL,
  `CID` VARCHAR(45) NULL,
  `Data_Agendamento` DATE NULL,
  PRIMARY KEY (`idEntity_Procedimento`),
  INDEX `FK_Paciente_idx` (`ID_Paciente` ASC) VISIBLE,
  INDEX `FK_Medico_idx` (`ID_Medico` ASC) VISIBLE,
  CONSTRAINT `FK_Paciente`
    FOREIGN KEY (`ID_Paciente`)
    REFERENCES `mydb`.`Entity_Usuario` (`idEntity_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Medico`
    FOREIGN KEY (`ID_Medico`)
    REFERENCES `mydb`.`Entity_Usuario_Medico` (`idEntity_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
